import { Lora } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/HomePage/Navbar";
import Footer from "@/Component/HomePage/Footer";

const lora = Lora({
  variable: "--font-main",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${lora.variable} h-full antialiased`}
    >
      <body className="font-main min-h-full flex flex-col w-full max-w-[1440px] mx-auto">
        <div 
        // className="sticky top-0 z-50"
        >
          <Navbar />
        </div>
        
        {children}
        <Footer />
        </body>
    </html>
  );
}
