import { Lora } from "next/font/google";
import "./globals.css";

const lora = Lora({
  variable: "--font-main",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${lora.variable} h-full antialiased`}
    >
      <body className="font-main min-h-full flex flex-col">{children}</body>
    </html>
  );
}
